#!/bin/sh
#!/bin/sh
gcc -O3 -DBUILD_CUSTOMCC -std=c++11 -I../secp256k1/include -I../univalue/include -I../cryptoconditions/include -I../cryptoconditions/src -I../cryptoconditions/src/asn -I.. -I. -fPIC -shared -c -o customcc.so cclib.cpp
cp customcc.so ../libcc.so
cd ..
make
cd cc
exit 0

if make -f Makefile_custom "$@"; then
  echo CUSTOMCC BUILD SUCCESSFUL
  cp customcc.so ../libcc.so
  cd .. 
  make 
else
  echo CUSTOMCC BUILD FAILED
  exit 1
fi
